# Generated by Django 4.2.16 on 2024-11-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный бонус')),
                ('title', models.CharField(max_length=255, verbose_name='Название бонуса')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание бонуса')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Сумма бонуса')),
            ],
            options={
                'verbose_name': 'Бонус',
                'verbose_name_plural': 'Бонусы',
                'ordering': ['-is_active', 'title'],
            },
        ),
    ]
