# Generated by Django 4.2.16 on 2024-11-23 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_product_article'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bonuses', '0002_bonus_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wb_username', models.CharField(max_length=255, verbose_name='Имя пользователя WB')),
                ('wb_id', models.CharField(max_length=255, unique=True, verbose_name='ID отзыва WB')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('review_date', models.DateField(verbose_name='Дата отзыва')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='BonusRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заявки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения заявки')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('status', models.CharField(choices=[('submitted', 'Подал заявку'), ('selected_article', 'Выбрал артикул'), ('selected_feedback', 'Выбрал отзыв'), ('sent_phone', 'Отправил телефон'), ('bonus_received', 'Получил бонус на телефон')], default='submitted', max_length=20, verbose_name='Статус')),
                ('feedback', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bonuses.feedback', verbose_name='Отзыв')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.product', verbose_name='Продукт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка на бонус',
                'verbose_name_plural': 'Заявки на бонус',
                'ordering': ['-created_at'],
            },
        ),
    ]
