# Generated by Django 4.2.16 on 2024-11-24 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_options'),
        ('bonuses', '0003_feedback_bonusrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonusrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='bonusrequest',
            name='bonus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bonuses.bonus', verbose_name='Бонусная программа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bonusrequest',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Клиент'),
            preserve_default=False,
        ),
    ]
