# Generated by Django 4.2.16 on 2024-11-24 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_options'),
        ('shops', '0002_product_article'),
        ('bonuses', '0004_remove_bonusrequest_user_bonusrequest_bonus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusrequest',
            name='bonus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bonuses.bonus', verbose_name='Бонусная программа'),
        ),
        migrations.AlterField(
            model_name='bonusrequest',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='bonusrequest',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops.product', verbose_name='Продукт'),
        ),
    ]
