# Generated by Django 4.2.16 on 2024-11-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonuses', '0005_alter_bonusrequest_bonus_alter_bonusrequest_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='review_date',
            field=models.DateTimeField(verbose_name='Дата отзыва'),
        ),
    ]
