# Generated by Django 4.2.16 on 2024-11-25 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_product_article'),
        ('bonuses', '0007_alter_bonusrequest_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusrequest',
            name='feedback',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bonuses.feedback', verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='bonusrequest',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops.product', verbose_name='Продукт'),
        ),
    ]
