# Generated by Django 4.2.16 on 2024-11-25 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonuses', '0008_alter_bonusrequest_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusrequest',
            name='feedback',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bonuses.feedback', verbose_name='Отзыв'),
        ),
    ]
