# Generated by Django 4.2.16 on 2024-11-25 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonuses', '0009_alter_bonusrequest_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonusrequest',
            name='feedback',
        ),
        migrations.AddField(
            model_name='feedback',
            name='bonus_request',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='bonuses.bonusrequest', verbose_name='Отзыв'),
            preserve_default=False,
        ),
    ]
