# Generated by Django 4.2.16 on 2024-11-25 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonuses', '0010_remove_bonusrequest_feedback_feedback_bonus_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='wb_id',
            new_name='wb_feedback_id',
        ),
    ]
