# Generated by Django 4.2.16 on 2024-12-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonuses', '0011_rename_wb_id_feedback_wb_feedback_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='pros',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Впечатления'),
        ),
    ]
