# Generated by Django 4.2.16 on 2024-11-18 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=1023)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='instructions/')),
            ],
        ),
        migrations.CreateModel(
            name='SubInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=1023)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='subinstructions/')),
                ('is_active', models.BooleanField(default=True)),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subinstructions', to='instructions.instruction')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
