# Generated by Django 4.2.16 on 2024-11-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='subinstruction',
            name='text',
            field=models.TextField(),
        ),
    ]
