# Generated by Django 4.2.16 on 2024-11-20 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0002_alter_instruction_text_alter_subinstruction_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='text',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(760)]),
        ),
        migrations.AlterField(
            model_name='subinstruction',
            name='text',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(760)]),
        ),
    ]
