# Generated by Django 4.2.16 on 2024-11-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0003_alter_instruction_text_alter_subinstruction_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/instructions/'),
        ),
        migrations.AlterField(
            model_name='subinstruction',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/subinstructions/'),
        ),
    ]
