# Generated by Django 4.2.16 on 2024-11-20 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0004_alter_instruction_photo_alter_subinstruction_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instruction',
            options={'verbose_name': 'Инструкция', 'verbose_name_plural': 'Инструкции'},
        ),
        migrations.AlterModelOptions(
            name='subinstruction',
            options={'ordering': ['order'], 'verbose_name': 'Подинструкция', 'verbose_name_plural': 'Подинструкции'},
        ),
    ]
