# Generated by Django 4.2.16 on 2024-11-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0005_alter_instruction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
