# Generated by Django 4.2.16 on 2024-11-20 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0006_instruction_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instruction',
            options={'ordering': ['order'], 'verbose_name': 'Инструкция', 'verbose_name_plural': 'Инструкции'},
        ),
    ]
