# Generated by Django 4.2.16 on 2024-11-20 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True, verbose_name='URL магазина')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/shops/', verbose_name='Фото магазина')),
                ('title', models.CharField(max_length=255, verbose_name='Название магазина')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен ли магазин')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание магазина')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True, verbose_name='URL продукта')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/products/', verbose_name='Фото продукта')),
                ('title', models.CharField(max_length=255, verbose_name='Название продукта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен ли продукт')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание продукта')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shops.shop', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
