# Generated by Django 4.2.16 on 2024-11-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='Артикул'),
        ),
    ]
