# Generated by Django 4.2.16 on 2024-11-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_product_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
