# Generated by Django 4.2.16 on 2024-11-28 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0003_alter_product_options_product_order'),
        ('clients', '0005_client_wb_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа')),
                ('question', models.TextField(blank=True, null=True, verbose_name='Вопрос')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('answered', 'Отвечен'), ('completed', 'Завершен')], default='created', max_length=10, verbose_name='Статус')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_requests', to='clients.client', verbose_name='Клиент')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_requests', to='shops.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Запрос в службу заботы',
                'verbose_name_plural': 'Запросы в службу заботы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CareRequestPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media/care_request_photos/', verbose_name='Фото запроса')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('care_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='care_requests.carerequest', verbose_name='Запрос в службу заботы')),
            ],
            options={
                'verbose_name': 'Фото запроса',
                'verbose_name_plural': 'Фото запросов',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
