# Generated by Django 4.2.16 on 2024-11-29 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('care_requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareRequestDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('text', 'Текст'), ('video', 'Видео'), ('audio', 'Аудио'), ('voice', 'Голосовое сообщение'), ('photo', 'Фото')], max_length=50)),
                ('file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('file_url', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='carerequest',
            name='question',
        ),
        migrations.DeleteModel(
            name='CareRequestPhoto',
        ),
        migrations.AddField(
            model_name='carerequestdetail',
            name='care_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='care_requests.carerequest'),
        ),
    ]
