# Generated by Django 4.2.16 on 2024-11-20 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
    ]
