# Generated by Django 4.2.16 on 2024-11-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='wb_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
